### ISSUE TITLE
cpp-suppress comments do not apply

### ISSUE THREAD

**Issue by SergeAyer** [loup-olivia/TSM_AES_2024-2025_AJ_LO#25]
In speedometer.hpp, // cppcheck-suppress unusedStructMember comments should be removed since they do not apply

**Comment by jonathanamezdroz** [comment]
* 0175d8a 12 seconds ago removede cpp check suppress - Jonathan Amez-Droz  (HEAD -> fixIssues)

**Comment by jonathanamezdroz** [comment]
in branch "fixIssues" will be merged with partIII

**Comment by jonathanamezdroz** [comment]
Added the comments again because otherwise cpp check returns false
