### ISSUE TITLE
The order in the initializer list do not match the order of declaration for some classes

### ISSUE THREAD

**Issue by SergeAyer** [loup-olivia/TSM_AES_2024-2025_AJ_LO#27]
Non-static data member are initialized in order of declaration in the class definition (see https://en.cppreference.com/w/cpp/language/constructor under Initialization order. The order in the initializer list used in the definition of your constructors should match the order of declaration.

**Comment by jonathanamezdroz** [comment]
in commit 93931d2 branch fixIssues, will be merged with BikeComputerPartIII

**Comment by jonathanamezdroz** [comment]
in commit 93931d2 branch fixIssues, will be merged with BikeComputerPartIII
